### ISSUE TITLE
Setuptools error on running nebulactl

### ISSUE THREAD

**Issue by s00500** [nebula-orchestrator/nebula-cmd#56]
## Expected/Wanted Behavior

Run nebulactl

## Actual Behavior

root@nebulatest:~# nebulactl 
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth_pkgres.py", line 13, in <module>
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/pkg_resources/__init__.py", line 85, in <module>

## Steps to Reproduce the Problem

  1. use the installer command from the readme on a blank debian or ubuntu machine
  2. Execute nebulactl

**Comment by naorlivne** [comment]
fixed in the latest release, the problem was TRAVIS not having an up-to-date version of setuptools & due to setuptools being outside of the requirements.txt file it wasn't caught by the bot I have running that updates packages.

You'll need to rerun the install command but should work afterwords

**Comment by s00500** [comment]
Awesome thanks!
